spring:
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8081

security:
  jwt:
    expiration-seconds: 3600
    private-key: |
      -----BEGIN PRIVATE KEY-----
      MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDhu8W5RNEaQbEh
      4NfOe5qK4Hh4fVwX6YVWKj2XZi5QHNkx9K2tzfQF4l52xTLyYj+W4qA3CGY4KCj7
      xQlVbD8/3V6RbhuYo0Nhj5dMztbeA7MrR+9nErJ/ewGv5axgk6x1sNtS9n6YubqJ
      brN0i8JrD0qaQnCa/rv6oL7+nANxvWVGm7X+8l2a5wQbv8c7QdWqC6U1j9MoAz2v
      Aq8N7fA8l1fypM6qfr5j8xZZjT6dUQIRVPOuBrd46yX4NfiVYhcnczuNaIYhGFnQ
      KG1pASUKbw5zk84S4MFKL26n8J5JjQwslBHO5A6iHq8o9SXlX0nyJmA/1gCq1R4L
      gMyWkzL5AgMBAAECggEAPvRdK2RuQLfRaRId6bN8df9r2MhMnbj97hYhifNauy2u
      4LQYfM1msVEZAJ0m6r0ad5B7Fv7J4Aiy6obm6gR3C2VfT0T9gt9Q1h3A9YxQ6j1S
      B6fQh6CGgZGwq3n1j8y3aLQslvJYK0lWnh9SpYw3Wm/Dbm1hJXGqC9dyl70Q+ycU
      f6bY2tPQ+fXN4im7A6+m9x8hTLB9N6jCR7aKSG7DN4WnUzxxZxk+EkO8BW6vJqHE
      aJmY4q9TMQkBVVrBczJjQmH1MriLBlKnSb57VJxzHohU7Yj8D38+8r4aS7Qh45le
      mXPfkgkKlkL+9g2D9eukQj0Y9mkqLdYZXNhM5r8q3QKBgQD+f9jM4YhWc1e7J5R5
      W35wJxwPq6D3GWpJzM6i4w3dphUFuY4mxXQpQj6QmP8rc1P9Y7Q0be2fW4I2mI0s
      L4JjAq0xQPYI5B8XWn7k+6sX9Y0l3m8OG4mDkQy2P1mR2bZc+2y2mF9L3vOd/vvR
      kyUlzCt+lyv0r0v9M0WkQm6O/QKBgQDjR2TNNubj6kz9zTml5k7nY1+QF9h5SBJ0
      cP8rj3h9e8hCjFceo4e3uV5m5TQ8YKv9x6KuQz+7z2TXu7Y+V70f1gE2xI2qjY2D
      M1zLY8jGbr8XWQ8hMhk2iAAq8H3CXhX2rW7fj5kVY6C4K1xkKJ9r4ZNoY4jYljQf
      m3vJBI9xhwKBgQDRUqYfX1m8T1fFmKtX7u+sQyEjtW3P2eQWk7w6xU2J3wJ4c+fz
      4AV5Q9nJz+8xikQ+E0xF1uSxWnOe3JY3g0bAU1qGNG7vYv9D0kwZxj6J7d+N9wxw
      yXfP9mJvpsli6l12Q3x+Lqv9S7xY8Fz5M0yQW+6yL0pkG1hR0iR5U0e+oQKBgA8m
      7S9aRbtw2oQd9x1FqIh5t4Q3rYVxwBq5x8K+e3L3wz3K5vM9Y7i9m8v6oWQW2n2w
      4YB5qD6eXxj8H7yY5d5mY7vD3xN7W5j9N6f9lQW1e4K5h4x8W7l6M8R3D5L9R8z4
      rVwY5fH6mQ9w4n5l2j9f7x2k3W1h9N8M7V5L4K3BAoGAVpD9fQ4w0r6n9tV3l7Q3
      X9n5Yz2gq7H7nV4r2k8u5l6p1m0o9n8b7v6c5x4z3a2s1d0f9g8h7j6k5l4m3n2o
      p1q2r3s4t5u6v7w8x9y0z1A2B3C4D5E6F7G8H9I=
      -----END PRIVATE KEY-----
    public-key: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4bvFuUTRGkGxIeDXznuaituB4eH1cF+mFVio9l2YuUBzZMfStrc30BeJedsUy8mI/luKgNwhmOCgo+8UJVWw/P91ekW4bmKNDYY+XTM7W3gOzK0fvZxKyf3sBr+WsYJOsdbDbUvZ+mLm6iW6zdIvCaw9KmkJwmv67+qC+/pwDcb1lRpu1/vJdmu cEG7/HO0HVqgulNY/TKAM9rwKvDe3wPJdX8qTOqn6+Y/MWWY0+nVEC EVTzrg a3eOsl+DX4lWIXJ3M7jWiGIRhZ0ChtaQElCm8Oc5POEuDBSi9up/CeSY0MLJQRzuQOoh6vKPUl5V9J8iZgP9YAqtUeC4DMlpMy+QIDAQAB
      -----END PUBLIC KEY-----
